AutomationOfWithdrawalBookletCharges/Controllers/AuditLogController.cs
using AutomationOfWithdrawalBookletCharges.Models;
using AutomationOfWithdrawalBookletCharges.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AutomationOfWithdrawalBookletCharges.Controllers
{
    [Authorize]
    public class AuditLogController : Controller
    {
        //
        // GET: /AuditLog/
        public ActionResult LoginLog(LoginLogViewModel model)
        {
            string strDate = String.Format("{0:MM/dd/yyyy}", model.SearchStartDate);
            string endDate = String.Format("{0:MM/dd/yyyy}", model.SearchEndDate);
            if (strDate == "" && endDate == "")
            {
                strDate = DateTime.Now.ToShortDateString();
                endDate = DateTime.Now.ToShortDateString();
            }
            var loginLogDetails = LoginLogModel.retrieveLoginLog(strDate, endDate);
            return View(loginLogDetails);
        }

        public ActionResult RequestLog(CustomerViewModel model, string login_id = null)
        {
            if (login_id == null)
            {
                string strDate = String.Format("{0:MM/dd/yyyy}", model.SearchStartDate);
                string endDate = String.Format("{0:MM/dd/yyyy}", model.SearchEndDate);
                if (strDate == "" && endDate == "")
                {
                    strDate = DateTime.Now.ToShortDateString();
                    endDate = DateTime.Now.ToShortDateString();
                }
                var RequestLogDetails = AuditLogModels.displayRequestLog(strDate, endDate, login_id);
                return View(RequestLogDetails);
            }
            else
            {
                var RequestLogDetails = AuditLogModels.displayRequestLog(null, null, login_id);
                return View(RequestLogDetails);
            }
            
        }

        public ActionResult PostingLog(PostingViewModel model, string login_id = null)
        {
            if (login_id == null)
            {
                string strDate = String.Format("{0:MM/dd/yyyy}", model.SearchStartDate);
                string endDate = String.Format("{0:MM/dd/yyyy}", model.SearchEndDate);
                if (strDate == "" && endDate == "")
                {
                    strDate = DateTime.Now.ToShortDateString();
                    endDate = DateTime.Now.ToShortDateString();
                }
                var CreditLogDetails = AuditLogModels.displayPostingLogCr(strDate, endDate, login_id);
                ViewBag.DebitLogDetails = AuditLogModels.displayPostingLogDr(strDate, endDate, login_id);
                return View(CreditLogDetails);
            }
            else
            {
                var CreditLogDetails = AuditLogModels.displayPostingLogCr(null, null, login_id);
                ViewBag.DebitLogDetails = AuditLogModels.displayPostingLogDr(null, null, login_id);
                return View(CreditLogDetails);
            }

        }
	}
}

AutomationOfWithdrawalBookletCharges/Controllers/HssaDetailsController.cs
using AutomationOfWithdrawalBookletCharges.LIB;
using AutomationOfWithdrawalBookletCharges.Models;
using AutomationOfWithdrawalBookletCharges.ViewModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace AutomationOfWithdrawalBookletCharges.Controllers
{
    [Authorize]
    public class HssaDetailsController : Controller
    {

        private static Random random = new Random();
        //
        // GET: /HssaDetails/
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.DisplayMessage = "List of Pending Request For " + DateTime.Now.ToLongDateString();
            CustomerModel RequestPool = new CustomerModel();   
            ModelState.Clear();
            var start_date = DateTime.Now.ToShortDateString();
            var end_date = DateTime.Now.ToShortDateString();
            var principal = (ClaimsIdentity)User.Identity;
            Claim branchcodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            string branchCode = branchcodeClaim.Value;
            return View(RequestPool.searchRequest(start_date,end_date,branchCode,"PENDING"));
        }

        [Authorize]
        [HttpPost]
        public ActionResult Search(CustomerViewModel model)
        {
            CustomerModel RequestPool = new CustomerModel();   
            var principal = (ClaimsIdentity)User.Identity;
            Claim branchcodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            string branchCode = branchcodeClaim.Value;
            string strDate = String.Format("{0:MM/dd/yyyy}", model.SearchStartDate);
            string endDate = String.Format("{0:MM/dd/yyyy}", model.SearchEndDate);
            string status = model.Status;
            
            if(strDate != null && endDate != null)
            {
                bool comp = String.Equals(strDate, endDate);
                if(comp == true)
                {
                    ViewBag.DisplayMessage = "List of " + ToTitleCase(status) + " For " + longDate(strDate);
                }
                else {
                    ViewBag.DisplayMessage = "List of " + ToTitleCase(status) + " Request From " + longDate(strDate) + " to " + longDate(endDate);
                }
            }
            return View("Index", RequestPool.searchRequest(strDate, endDate, branchCode, status));
            
            
        }

        [Authorize]
        public ActionResult Display(string id)
        {
            CustomerModel details = new CustomerModel();
            var principal = (ClaimsIdentity)User.Identity;
            Claim branchcodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            string branchCode = branchcodeClaim.Value;
            return View(details.displayRequestDetails(id, branchCode).FirstOrDefault());
        }
        public ActionResult DisplayState(string id)
        {
            CustomerModel details = new CustomerModel();
            var principal = (ClaimsIdentity)User.Identity;
            Claim branchcodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            string branchCode = branchcodeClaim.Value;
            return View("DisplayState",details.displayRequestDetails(id, branchCode).FirstOrDefault());
        }

        [Authorize,HttpPost]
        public ActionResult Approve(CustomerViewModel model)
        {
            PostingServices postClient = new PostingServices();
            SendEmail mailHssa = new SendEmail();
            var principal = (ClaimsIdentity)User.Identity;
            Claim empNumClaim = principal.FindFirst(ClaimTypes.SerialNumber);
            Claim loginIdClaim = principal.FindFirst(ClaimTypes.Actor);
            Claim branchCodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            var name = principal.FindFirst(ClaimTypes.GivenName).Value;
            var body = "";
            ViewBag.Message = "";
            string branchCode = branchCodeClaim.Value;
            int loginId = Convert.ToInt32(loginIdClaim.Value);        
            string batchId = RandomString(23);
            string payRef = RandomString(23);
            string empNum = empNumClaim.Value;//debit flexcube
            var emailParams = CustomerModel.sentToSsaParams(model);
            var emailparameters = emailParams.FirstOrDefault();
            List<string> repEmail = new List<string>(); repEmail.Add(emailparameters.Email);
            var title = "RE: Withdrawal Booklet Request for " + emailparameters.AccountNumber;
            string postingStat = postClient.postingTransaction(branchCode, model.AccountNumber, batchId, payRef, model.RequestId);
            if (postingStat == "SUCCESSFUL")
            {
                var ssaEmail = CustomerModel.UpdateRecord(model, empNum, loginId, branchCode, "APPROVED");
                body = "<p>Hello " + emailparameters.SsaName + ",<p><p>The booklet request for the customer " + emailparameters.AccountName +
                " with account number " + emailparameters.AccountNumber + " have be authorized for issuance, kindly issue the booklet to the customer.";
                ViewBag.Message = "ISSUANCE SUCCESSFULLY COMPLETED";
            }               
            else
            {
                body = "<p>Hello " + emailparameters.SsaName + ",<p><p>The booklet request for the customer " + emailparameters.AccountName +
                " with account number " + emailparameters.AccountNumber + " cannot be processed at the moment.";
                ViewBag.Message = "ISSUANCE UNSUCCESSFUL (ACCOUNT NOT DEBITED)";
            }
            mailHssa.SendEmailWithoutAttachment(name, title, body, "", repEmail);
            return View("Message");
        }

        [Authorize, HttpPost]
        public ActionResult Decline(CustomerViewModel model)
        {
            SendEmail mailHssa = new SendEmail();
            var principal = (ClaimsIdentity)User.Identity;
            var name = principal.FindFirst(ClaimTypes.GivenName).Value;
            Claim empNumClaim = principal.FindFirst(ClaimTypes.SerialNumber);
            Claim loginIdClaim = principal.FindFirst(ClaimTypes.Actor);
            Claim branchCodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            string branchCode = branchCodeClaim.Value;
            int loginId = Convert.ToInt32(loginIdClaim.Value);
            string empNum = empNumClaim.Value;
            var ssaEmail = CustomerModel.UpdateRecord(model, empNum, loginId, branchCode, "DECLINED");
            var emailParams = CustomerModel.sentToSsaParams(model);
            var emailparameters = emailParams.FirstOrDefault();
            List<string> repEmail = new List<string>(); repEmail.Add(emailparameters.Email);
            var body = "<p>Hello "+ emailparameters.SsaName +",<p><p>The booklet request for the customer "+emailparameters.AccountName+  
            " with account number " +emailparameters.AccountNumber +
            " have been declined. <br/> Reason: "
                + emailparameters.Comment ;
            var title = "RE: Withdrawal Booklet Request for " + emailparameters.AccountNumber;

            mailHssa.SendEmailWithoutAttachment(name, title, body, "", repEmail);
            ViewBag.Message = "REQUEST HAVE BEEN DECLINED";
            return View("Message");
        }

        //counting request with pending status.
        public string countReq()
        {
            string branchCode = "";
            string reqNum = "";
            var principal = (ClaimsIdentity)User.Identity;
            Claim branchCodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            try { 
            branchCode = branchCodeClaim.Value;
            reqNum = CustomerModel.countRequest(branchCode, "PENDING");
            }
            catch
            {
                reqNum = "0";
            }
            return reqNum;
        }

        private string ToTitleCase(string str)
        {
            return CultureInfo.CurrentCulture.TextInfo.ToTitleCase(str.ToLower());
        }

        public static string RandomString(int length)
        {
            const string chars = "0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        private string longDate(string dates)
        {
            DateTime dt = DateTime.ParseExact(dates, "MM/dd/yyyy", CultureInfo.InvariantCulture);
            string newdt = dt.ToLongDateString();
            return newdt;
        }

        public static string Truncate(string source, int length)
        {
            return source.Substring(0, Math.Min(length, source.Length));
        }

        //Reporting
        public ActionResult Report()
        {
            ViewBag.DisplayMessage = "Total Issued Booklets for " + DateTime.Now.ToLongDateString();
            ViewBag.Title = "Total Issued Booklets for " + DateTime.Now.ToLongDateString();
            CustomerModel RequestPool = new CustomerModel();
            ModelState.Clear();
            var start_date = DateTime.Now.ToShortDateString();
            var end_date = DateTime.Now.ToShortDateString();
            var principal = (ClaimsIdentity)User.Identity;
            Claim branchcodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            string branchCode = branchcodeClaim.Value;
            return View(RequestPool.searchReport(start_date, end_date, branchCode, "APPROVED"));
        }

        [Authorize]
        [HttpPost]
        public ActionResult ReportSearch(CustomerViewModel model)
        {
            CustomerModel RequestPool = new CustomerModel();
            var principal = (ClaimsIdentity)User.Identity;
            Claim branchcodeClaim = principal.FindFirst(ClaimTypes.PostalCode);
            string branchCode = branchcodeClaim.Value;
            string strDate = String.Format("{0:MM/dd/yyyy}", model.SearchStartDate);

AutomationOfWithdrawalBookletCharges/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="X-Frame-Options" content="SAMEORIGIN">
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/favicon.ico" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Withdrawal Booklet Manager", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_Menu")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
       
        
    </div>
    <div class="page-footer" role="navigation">
        <div class="container-fluid">
            <footer>
                <p class="ubn-color">@DateTime.Now.Year &copy; Union Bank of Nigeria. Powered by DevOps.</p>
            </footer>
        </div>
    </div>


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/datepicker")
        @Scripts.Render("~/bundles/countreq")
        @RenderSection("Script", required: false)
</body>
</html>

AutomationOfWithdrawalBookletCharges/Views/Shared/_Menu.cshtml
@using System.Security.Claims;

@if (Request.IsAuthenticated)
{
    var identity = (ClaimsIdentity)User.Identity;
    var name = identity.FindFirst(ClaimTypes.GivenName).Value;
    var userRole = identity.FindFirst(ClaimTypes.Role).Value;
    string urlActio = "";
    string urlCon = "";
    switch(userRole)
    {
        case "Administrator":  urlActio = "LogOff";  urlCon = "Admin";
            break;
        case "Admin": urlActio = "LogOff";  urlCon = "Admin";
            break;
        case "Checker": urlActio = "LogOff"; urlCon = "HssaChecker";
            break;
        default:  urlActio = "LogOff";  urlCon = "Home";
            break;
    }
    using (Html.BeginForm(urlActio, urlCon, FormMethod.Post, new { id = "logoutForm" }))
    {
        @Html.AntiForgeryToken()

<ul class="nav navbar-nav">
    @if (User.IsInRole("Admin") || User.IsInRole("Administrator"))
    {
    <li>
        <a href="@Url.Action("Index", "AdminDetails")" class="white-bar"><span  class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;&nbsp;Home</a>
    </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle white-bar" data-toggle="dropdown"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Audit Log <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="@Url.Action("LoginLog", "AuditLog")"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Login/Logout</a>
                </li>
                <li>
                    <a href="@Url.Action("RequestLog", "AuditLog")"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Booklet request initiated</a>
                </li>
                <li>
                    <a href="@Url.Action("PostingLog", "AuditLog")"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Posting Transactions</a>
                </li>
            </ul>
        </li>
    }
    @if (User.IsInRole("Checker"))
    {
        <li class="dropdown">
            <a href="#" class="dropdown-toggle white-bar" data-toggle="dropdown"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Reports <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="@Url.Action("Report", "HssaDetails")"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Total Issued Booklets</a>
                </li>
               
            </ul>
        </li>
        <li>
            <a href="@Url.Action("Index","HssaDetails")" class="white-bar">Pending Request <span id="count" class="label label-danger"></span></a>
        </li>
    }
    @if (User.IsInRole("Maker"))
    {
    <li>
        <a href="@Url.Action("Index", "AccountCheck")" class="white-bar"><span  class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;&nbsp;Home</a>
    </li>
    <li class="dropdown">
            <a href="#" class="dropdown-toggle white-bar" data-toggle="dropdown"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Daily Request <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>
                    <a href="@Url.Action("RequestList", "AccountCheck", new { id = "PENDING"})"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Pending</a>
                </li>
                <li>
                    <a href="@Url.Action("RequestList", "AccountCheck", new { id = "APPROVED"})"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Approved</a>
                </li>
                <li>
                    <a href="@Url.Action("RequestList", "AccountCheck", new { id = "DECLINED"})"><span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;&nbsp;Declined</a>
                </li>
            </ul>
        </li>
    }
</ul>

    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="#" class="white-bar"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;&nbsp;@name</a>
        </li>
        <li>
            <a href="javascript:document.getElementById('logoutForm').submit()" class="white-bar"><span class="glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;&nbsp;Log off</a>
        </li>
    </ul>
    }
}